### ISSUE TITLE
Unqualified dereference in `RequireConstructorPropertyPromotionSniff::areTypeHintEqual`

### ISSUE THREAD

**Issue by nederdirk** [slevomat/coding-standard#1247]
While trying to upgrade this library to version 7.0.11, our build failed because PHP_CodeSniffer crashed:
```
PHP Fatal error:  Uncaught Error: Call to a member function getTypeHint() on null in /home/runner/work/marketphase/marketphase/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/RequireConstructorPropertyPromotionSniff.php:331
Stack trace:
#0 /home/runner/work/marketphase/marketphase/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/RequireConstructorPropertyPromotionSniff.php(143): SlevomatCodingStandard\Sniffs\Classes\RequireConstructorPropertyPromotionSniff->areTypeHintEqual()
#1 /home/runner/work/marketphase/marketphase/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): SlevomatCodingStandard\Sniffs\Classes\RequireConstructorPropertyPromotionSniff->process()
#2 /home/runner/work/marketphase/marketphase/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
#3 /home/runner/work/marketphase/marketphase/vendor/squizlabs/php_codesniffer/src/Runner.php(630): PHP_CodeSniffer\Files\LocalFile->process()
#4 /home/runner/work/marketphase/marketphase/vendor/squizlabs/php_codesniffer/src/Runner.php(434): PHP_CodeSniffer\Runner->processFile()
#5 /home/runner/work/marketphase/marketphase/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#6 /home/runner/work/marketphase/marketphase/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#7 {main}
  thrown in /home/runner/work/marketphase/marketphase/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/RequireConstructorPropertyPromotionSniff.php on line 331
```

I submitted a patch (#1246) but I'm arguably too dumb to make a meaningful contribution to this project.

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/2ebe0c61632890676ca9b7d181c158b26248619a
