### ISSUE TITLE
TypeError on AnnotationTypeHelper.php:477

### ISSUE THREAD

**Issue by alies-dev** [slevomat/coding-standard#1349]
package version: 7.1.0
php version: 8.1.3

```

PHP Fatal error:  Uncaught TypeError: SlevomatCodingStandard\Helpers\AnnotationTypeHelper::containsOneType(): Argument #1 ($typeNode) must be of type PHPStan\PhpDocParser\Ast\Type\TypeNode, null given, called in /Users/me/code/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/TypeHints/ReturnTypeHintSniff.php on line 249 and defined in /Users/me/code/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationTypeHelper.php:477
Stack trace:
#0 /Users/me/code/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/TypeHints/ReturnTypeHintSniff.php(249): SlevomatCodingStandard\Helpers\AnnotationTypeHelper::containsOneType(NULL)
#1 /Users/me/code/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/TypeHints/ReturnTypeHintSniff.php(117): SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff->checkFunctionTypeHint(Object(PHP_CodeSniffer\Files\LocalFile), 106, NULL, NULL, Array)
#2 /Users/me/code/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 106)
#3 /Users/me/code/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
#4 /Users/me/code/vendor/squizlabs/php_codesniffer/src/Runner.php(631): PHP_CodeSniffer\Files\LocalFile->process()
#5 /Users/me/code/vendor/squizlabs/php_codesniffer/src/Runner.php(434): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#6 /Users/me/code/vendor/squizlabs/php_codesniffer/src/Runner.php(200): PHP_CodeSniffer\Runner->run()
#7 /Users/me/code/vendor/squizlabs/php_codesniffer/bin/phpcbf(18): PHP_CodeSniffer\Runner->runPHPCBF()
#8 /Users/me/code/vendor/bin/phpcbf(117): include('/Users/me/co...')
#9 {main}
  thrown in /Users/me/code/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationTypeHelper.php on line 477

Fatal error: Uncaught TypeError: SlevomatCodingStandard\Helpers\AnnotationTypeHelper::containsOneType(): Argument #1 ($typeNode) must be of type PHPStan\PhpDocParser\Ast\Type\TypeNode, null given, called in /Users/me/code/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/TypeHints/ReturnTypeHintSniff.php on line 249 and defined in /Users/me/code/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationTypeHelper.php:477
Stack trace:
#0 /Users/me/code/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/TypeHints/ReturnTypeHintSniff.php(249): SlevomatCodingStandard\Helpers\AnnotationTypeHelper::containsOneType(NULL)
#1 /Users/me/code/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/TypeHints/ReturnTypeHintSniff.php(117): SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff->checkFunctionTypeHint(Object(PHP_CodeSniffer\Files\LocalFile), 106, NULL, NULL, Array)
#2 /Users/me/code/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 106)
#3 /Users/me/code/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
#4 /Users/me/code/vendor/squizlabs/php_codesniffer/src/Runner.php(631): PHP_CodeSniffer\Files\LocalFile->process()
#5 /Users/me/code/vendor/squizlabs/php_codesniffer/src/Runner.php(434): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#6 /Users/me/code/vendor/squizlabs/php_codesniffer/src/Runner.php(200): PHP_CodeSniffer\Runner->run()
#7 /Users/me/code/vendor/squizlabs/php_codesniffer/bin/phpcbf(18): PHP_CodeSniffer\Runner->runPHPCBF()
#8 /Users/me/code/vendor/bin/phpcbf(117): include('/Users/me/co...')
#9 {main}
  thrown in /Users/me/code/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationTypeHelper.php on line 477
```

I'll try to locate the code that produce this error and post is as a separate message

**Comment by kukulich** [comment]
> phpcbf fails on SlevomatCodingStandard.Classes.RequireAbstractOrFinal when a non-abstract classes extended by another one, it changes parent to final and thus final can't extend final 

It's not a bug. It's just how PHPCS works.

**Comment by lptn** [comment]
Thanks!

Also, for somereason this class-level suppression doesn't work: `@phpcsSuppress SlevomatCodingStandard.Classes.RequireAbstractOrFinal.ClassNeitherAbstractNorFinal`:
```php
/**
 * @noRector \Rector\Privatization\Rector\Class_\FinalizeClassesWithoutChildrenRector
 * @phpcsSuppress SlevomatCodingStandard.Classes.RequireAbstractOrFinal.ClassNeitherAbstractNorFinal
 */
class Section extends Resource {}


final class OrderedSection extends Section {}
```

**Comment by kukulich** [comment]
@lptn Use `@phpcs:disable SlevomatCodingStandard.Classes.RequireAbstractOrFinal`

**Comment by lptn** [comment]
I'm sorry for asking this and taking your time, but I was always had a hard time to find differences between `@phpcs:disable` vs `@phpcssuppress`, do you know any docs where it's described? What what I know, `phpcs:disable` has a "pair" `phpcs:enable`, I assume that's it (`@phpcssuppress` can't be enabled again within the file). But this case proved me they have different behaviour.
