### ISSUE TITLE
`SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff` crashes on invalid docblock

### ISSUE THREAD

**Issue by BackEndTea** [slevomat/coding-standard#1382]
The sniff crashed on the following docblock:

```php
    /**
     * @param $prefix
     *
     * @return string
     */
    public static function generateDiscountCode($prefix) 
    // function body
```

```
        *** START ADDITIONAL PHP PROCESSING ***
        * token 832 on line 151 changed from T_OPEN_SQUARE_BRACKET to T_OPEN_SHORT_ARRAY
        * token 836 on line 151 changed from T_CLOSE_SQUARE_BRACKET to T_CLOSE_SHORT_ARRAY
        * token 652 on line 136 changed from T_OPEN_SQUARE_BRACKET to T_OPEN_SHORT_ARRAY
        * token 683 on line 136 changed from T_CLOSE_SQUARE_BRACKET to T_CLOSE_SHORT_ARRAY
        * token 549 on line 111 changed from T_OPEN_SQUARE_BRACKET to T_OPEN_SHORT_ARRAY
        * token 644 on line 135 changed from T_CLOSE_SQUARE_BRACKET to T_CLOSE_SHORT_ARRAY
        * token 459 on line 95 changed from T_OPEN_SQUARE_BRACKET to T_OPEN_SHORT_ARRAY
        * token 463 on line 95 changed from T_CLOSE_SQUARE_BRACKET to T_CLOSE_SHORT_ARRAY
        * token 393 on line 80 changed from T_OPEN_SQUARE_BRACKET to T_OPEN_SHORT_ARRAY
        * token 428 on line 85 changed from T_CLOSE_SQUARE_BRACKET to T_CLOSE_SHORT_ARRAY
        * token 311 on line 65 changed from T_OPEN_SQUARE_BRACKET to T_OPEN_SHORT_ARRAY
        * token 315 on line 65 changed from T_CLOSE_SQUARE_BRACKET to T_CLOSE_SHORT_ARRAY
        * token 236 on line 48 changed from T_OPEN_SQUARE_BRACKET to T_OPEN_SHORT_ARRAY
        * token 279 on line 54 changed from T_CLOSE_SQUARE_BRACKET to T_CLOSE_SHORT_ARRAY
        * token 151 on line 33 changed from T_OPEN_SQUARE_BRACKET to T_OPEN_SHORT_ARRAY
        * token 158 on line 33 changed from T_CLOSE_SQUARE_BRACKET to T_CLOSE_SHORT_ARRAY
        * token 75 on line 15 changed from T_OPEN_SQUARE_BRACKET to T_OPEN_SHORT_ARRAY
        * token 118 on line 21 changed from T_CLOSE_SQUARE_BRACKET to T_CLOSE_SHORT_ARRAY
        *** END ADDITIONAL PHP PROCESSING ***
[PHP => 878 tokens in 159 lines]... 
        *** START TOKEN PROCESSING ***
                Process token 0: T_OPEN_TAG => <?php\n
                        Processing PHP_CodeSniffer\Standards\PSR2\Sniffs\Files\ClosingTagSniff... DONE in 0.0003 seconds
                        Processing PHP_CodeSniffer\Standards\PSR2\Sniffs\Files\EndFileNewlineSniff... DONE in 0.0002 seconds
                        Processing PHP_CodeSniffer\Standards\PSR1\Sniffs\Files\SideEffectsSniff... DONE in 0.0001 seconds
                        Processing PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\DisallowAlternativePHPTagsSniff... DONE in 0 seconds
                        Processing PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\DisallowShortOpenTagSniff... DONE in 0 seconds
                        Processing PHP_CodeSniffer\Standards\Generic\Sniffs\Files\LineEndingsSniff... DONE in 0 seconds
                        Processing PHP_CodeSniffer\Standards\Generic\Sniffs\Files\LineLengthSniff... DONE in 0.0006 seconds
                        Processing PHP_CodeSniffer\Standards\Squiz\Sniffs\WhiteSpace\SuperfluousWhitespaceSniff... DONE in 0 seconds
                        Processing PHP_CodeSniffer\Standards\Generic\Sniffs\WhiteSpace\ScopeIndentSniff... DONE in 0.0036 seconds
                        Processing PHP_CodeSniffer\Standards\Generic\Sniffs\WhiteSpace\DisallowTabIndentSniff... DONE in 0.0009 seconds
                        Processing PHPCompatibility\Sniffs\Upgrade\LowPHPCSSniff... DONE in 0 seconds
                        Processing PHPCompatibility\Sniffs\Upgrade\LowPHPSniff... DONE in 0 seconds
                        Processing PHPCompatibility\Sniffs\Miscellaneous\RemovedAlternativePHPTagsSniff... DONE in 0.0001 seconds
                        Processing PHPCompatibility\Sniffs\Miscellaneous\NewPHPOpenTagEOFSniff... DONE in 0 seconds
                        Processing PHP_CodeSniffer\Standards\Generic\Sniffs\Classes\DuplicateClassNameSniff... DONE in 0.0005 seconds
                        Processing PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\CharacterBeforePHPOpeningTagSniff... DONE in 0 seconds
                        Processing SlevomatCodingStandard\Sniffs\Namespaces\AlphabeticallySortedUsesSniff... DONE in 0.003 seconds
                        Processing SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff... PHP Fatal error:  Uncaught TypeError: SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation::__construct(): Argument #5 ($contentNode) must be of type ?PHPStan\PhpDocParser\Ast\PhpDoc\ParamTagValueNode, PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode given, called in /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php on line 357 and defined in /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/ParameterAnnotation.php:31
Stack trace:
#0 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php(357): SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation->__construct('@param', 504, 506, '$prefix', Object(PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode))
#1 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(42): SlevomatCodingStandard\Helpers\AnnotationHelper::SlevomatCodingStandard\Helpers\{closure}()
#2 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(31): SlevomatCodingStandard\Helpers\SniffLocalCache::setIfNotCached(0, '/Volumes/Source...', Object(Closure))
#3 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php(372): SlevomatCodingStandard\Helpers\SniffLocalCache::getAndSetIfNotCached(Object(PHP_CodeSniffer\Files\LocalFile), 'annotations-499', Object(Closure))
#4 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Namespaces/UnusedUsesSniff.php(141): SlevomatCodingStandard\Helpers\AnnotationHelper::getAnnotations(Object(PHP_CodeSniffer\Files\LocalFile), 499)
#5 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 0)
#6 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(130): PHP_CodeSniffer\Files\File->process()
#7 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/squizlabs/php_codesniffer/src/Runner.php(628): PHP_CodeSniffer\Files\LocalFile->process()
#8 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/squizlabs/php_codesniffer/src/Runner.php(434): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#9 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#10 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#11 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/bin/phpcs(117): include('/Volumes/Source...')
#12 {main}
  thrown in /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/ParameterAnnotation.php on line 31

Fatal error: Uncaught TypeError: SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation::__construct(): Argument #5 ($contentNode) must be of type ?PHPStan\PhpDocParser\Ast\PhpDoc\ParamTagValueNode, PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode given, called in /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php on line 357 and defined in /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/ParameterAnnotation.php:31
Stack trace:
#0 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php(357): SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation->__construct('@param', 504, 506, '$prefix', Object(PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode))
#1 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(42): SlevomatCodingStandard\Helpers\AnnotationHelper::SlevomatCodingStandard\Helpers\{closure}()
#2 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(31): SlevomatCodingStandard\Helpers\SniffLocalCache::setIfNotCached(0, '/Volumes/Source...', Object(Closure))
#3 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php(372): SlevomatCodingStandard\Helpers\SniffLocalCache::getAndSetIfNotCached(Object(PHP_CodeSniffer\Files\LocalFile), 'annotations-499', Object(Closure))
#4 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Namespaces/UnusedUsesSniff.php(141): SlevomatCodingStandard\Helpers\AnnotationHelper::getAnnotations(Object(PHP_CodeSniffer\Files\LocalFile), 499)
#5 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 0)
#6 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(130): PHP_CodeSniffer\Files\File->process()
#7 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/squizlabs/php_codesniffer/src/Runner.php(628): PHP_CodeSniffer\Files\LocalFile->process()
#8 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/squizlabs/php_codesniffer/src/Runner.php(434): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#9 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#10 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#11 /Volumes/SourceCode/Work/composer-packages/my_project/vendor/bin/phpcs(117): include('/Volumes/Source...')
#12 {main}
  thrown in /Volumes/SourceCode/Work/composer-packages/my_project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/ParameterAnnotation.php on line 31

```

**Comment by kukulich** [comment]
Looks like a duplicate to https://github.com/slevomat/coding-standard/issues/1379

**Comment by BackEndTea** [comment]
Ah my bad, i completely missed that.
