### ISSUE TITLE
phpstan/phpdoc-parser 1.6.0 introduced a breaking change for slevomat/coding-standard

### ISSUE THREAD

**Issue by Levivb** [slevomat/coding-standard#1384]
Hey,

`phpstan/phpdoc-parser` introduced a change which under certain code, let the code sniffer crash in `SlevomatCodingStandard` code.

The diff from the `phpstan/phpdoc-parser` update is https://github.com/phpstan/phpdoc-parser/compare/1.5.1...1.6.0

The code to reproduce the crash:
```php
<?php

class SomeClass
{
    /**
     * @param $somevar
     */
    public function somefunc($somevar)
    {
    }
}
```

The issue here seems to be the `@param $somevar` docblock which lacks a typehint

A code fix would be to remove the docblock
```diff
-     /**
-      * @param $somevar
-      */
```

or adding a typehint
```diff
    /**
-      * @param $somevar
+      * @param mixed $somevar
     */
```

But since the code sniffer crashes, it fails to report which file triggers the crash.

The stacktrace of the crash:
```
composer style App/SomeClass.php
> vendor/bin/phpcs --standard=phpcs.xml 'app/SomeClass.php' '-s'

Fatal error: Uncaught TypeError: SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation::__construct(): Argument #5 ($contentNode) must be of type ?PHPStan\PhpDocParser\Ast\PhpDoc\ParamTagValueNode, PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode given, called in myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php on line 357 and defined in myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/ParameterAnnotation.php:31
Stack trace:
#0 myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php(357): SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation->__construct('@param', 29, 31, '$somevar', Object(PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode))
#1 myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(42): SlevomatCodingStandard\Helpers\AnnotationHelper::SlevomatCodingStandard\Helpers\{closure}()
#2 myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(31): SlevomatCodingStandard\Helpers\SniffLocalCache::setIfNotCached(0, '/Users/levi/Doc...', Object(Closure))
#3 myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php(372): SlevomatCodingStandard\Helpers\SniffLocalCache::getAndSetIfNotCached(Object(PHP_CodeSniffer\Files\LocalFile), 'annotations-24', Object(Closure))
#4 myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Namespaces/UnusedUsesSniff.php(141): SlevomatCodingStandard\Helpers\AnnotationHelper::getAnnotations(Object(PHP_CodeSniffer\Files\LocalFile), 24)
#5 myproject/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 0)
#6 myproject/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
#7 myproject/vendor/squizlabs/php_codesniffer/src/Runner.php(631): PHP_CodeSniffer\Files\LocalFile->process()
#8 myproject/vendor/squizlabs/php_codesniffer/src/Runner.php(503): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#9 myproject/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#10 myproject/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#11 myproject/vendor/bin/phpcs(117): include('/Users/levi/Doc...')
#12 {main}
  thrown in myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/ParameterAnnotation.php on line 31
E 1 / 1 (100%)

Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: One or more child processes failed to run in myproject/vendor/squizlabs/php_codesniffer/src/Runner.php:545
Stack trace:
#0 myproject/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#1 myproject/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#2 myproject/vendor/bin/phpcs(117): include('/Users/levi/Doc...')
#3 {main}
  thrown in myproject/vendor/squizlabs/php_codesniffer/src/Runner.php on line 545
Script vendor/bin/phpcs --standard=phpcs.xml handling the style event returned with error code 255
```

The following rule triggers the crash: `SlevomatCodingStandard.Commenting.UselessFunctionDocComment` (with or without properties). But for example `SlevomatCodingStandard.TypeHints.PropertyTypeHint` also trigger the same crash. (also with or without properties)

I hope you know how to fix this one :D

**Comment by Levivb** [comment]
Oh... duplicate of https://github.com/slevomat/coding-standard/issues/1382 and https://github.com/slevomat/coding-standard/issues/1379

sorry 😅 

great work on the fix!
