### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by mimmi20** [slevomat/coding-standard#1397]
I got this fatal error:

```php
PHP Fatal error:  Uncaught TypeError: Argument 5 passed to SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation::__construct() must be an instance of PHPStan\PhpDocParser\Ast\PhpDoc\ParamTagValueNode or null, instance of PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode given, called in ../build/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php on line 357 and defined in ../build/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/ParameterAnnotation.php:31
Stack trace:
#0 ../build/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php(357): SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation->__construct()
#1 ../build/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(42): SlevomatCodingStandard\Helpers\Annotati in ../build/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/ParameterAnnotation.php on line 31
```

I used the following versions:
- PHP: 7.4.3
- "slevomat/coding-standard": 7.2.1
- "phpstan/phpstan": 1.7.15

At the moment I can not upgrade to version 8+ because the Doctine Coding Standard does not support this version yet.

**Comment by kukulich** [comment]
> At the moment I can not upgrade to version 8+ because the Doctine Coding Standard does not support this version yet.

You can try dev version of Doctine Coding Standard.
