### ISSUE TITLE
Try to avoid fatal errors for incomplete function syntax

### ISSUE THREAD

**Issue by ocean90** [slevomat/coding-standard#1415]
I'm using PHPCS in my editor while coding. This does work fine so far. But recently I'm getting a few fatal errors when starting to write a new function like `function foo` until I have finished the syntax.

Steps to reproduce:

* Create `test.php` with `<?php function foo`
* Run `phpcs --standard=SlevomatCodingStandard test.php`

```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to SlevomatCodingStandard\Helpers\TokenHelper::findNext() must be of the type int, null given, called in ~/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ReferencedNameHelper.php on line 139 and defined in ~/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/TokenHelper.php:126
Stack trace:
#0 ~/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ReferencedNameHelper.php(139): SlevomatCodingStandard\Helpers\TokenHelper::findNext(Object(PHP_CodeSniffer\Files\LocalFile), Array, NULL)
#1 ~/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ReferencedNameHelper.php(67): SlevomatCodingStandard\Helpers\ReferencedNameHelper::createAllReferencedNames(Object(PHP_CodeSniffer\Files\LocalFile), 0)
#2 ~/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(42): SlevomatCodingStandard\Helpers\R in ~/.composer/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/TokenHelper.php on line 126
```

Do you think an additional check can be added to avoid the fatal error?

**Comment by kukulich** [comment]
Please check the recommendation in installation guide: https://github.com/slevomat/coding-standard#installation
