### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 5 passed to SlevomatCodingStandard\Helpers\Annotation\AssertAnnotation

### ISSUE THREAD

**Issue by loevgaard** [slevomat/coding-standard#1423]
I am getting this exception when using this library through ECS. I am using version 7.2, but I am afraid I don't know how to reproduce this error, but maybe the stack trace will give some insight:

```
PHP Fatal error:  Uncaught TypeError: Argument 5 passed to SlevomatCodingStandard\Helpers\Annotation\AssertAnnotation::__construct() must be an instance of PHPStan\PhpDocParser\Ast\PhpDoc\AssertTagValueNode or null, instance of PHPStan\PhpDocParser\Ast\PhpDoc\AssertTagPropertyValueNode given, called in /home/runner/work/sylius/sylius/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php on line 357 and defined in /home/runner/work/sylius/sylius/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/AssertAnnotation.php:21
Stack trace:
#0 /home/runner/work/sylius/sylius/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php(357): SlevomatCodingStandard\Helpers\Annotation\AssertAnnotation->__construct()
#1 /home/runner/work/sylius/sylius/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(42): SlevomatCodingStandard\Helpers\AnnotationHelper::SlevomatCodingStandard\Helpers\{closure}()
#2 /home/runner/work/sylius/sylius/ven in /home/runner/work/sylius/sylius/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/AssertAnnotation.php on line 21
Script ecs check handling the check-style event returned with error code 255
```

**Comment by kukulich** [comment]
Just use latest version of this library.

**Comment by loevgaard** [comment]
Thank you :)
