### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError with SlevomatCodingStandard.Namespaces.UnusedUses

### ISSUE THREAD

**Issue by michnovka** [slevomat/coding-standard#1431]
using

```xml
<rule ref="SlevomatCodingStandard.Namespaces.UnusedUses">
    <properties>
        <property name="searchAnnotations" value="true"/>
    </properties>
</rule>
```
I get

```
PHP Fatal error:  Uncaught TypeError: SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation::__construct(): Argument #5 ($contentNode) must be of type ?PHPStan\PhpDocParser\Ast\PhpDoc\ParamTagValueNode, PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode given, called in /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php on line 357 and defined in /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/ParameterAnnotation.php:31
Stack trace:
#0 /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php(357): SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation->__construct()
#1 /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(42): SlevomatCodingStandard\Helpers\AnnotationHelper::SlevomatCodingStandard\Helpers\{closure}()
#2 /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(31): SlevomatCodingStandard\Helpers\SniffLocalCache::setIfNotCached()
#3 /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php(372): SlevomatCodingStandard\Helpers\SniffLocalCache::getAndSetIfNotCached()
#4 /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Namespaces/UnusedUsesSniff.php(141): SlevomatCodingStandard\Helpers\AnnotationHelper::getAnnotations()
#5 /home/superuser/slevomatErrorPOC/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff->process()
#6 /home/superuser/slevomatErrorPOC/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(130): PHP_CodeSniffer\Files\File->process()
#7 /home/superuser/slevomatErrorPOC/vendor/squizlabs/php_codesniffer/src/Runner.php(628): PHP_CodeSniffer\Files\LocalFile->process()
#8 /home/superuser/slevomatErrorPOC/vendor/squizlabs/php_codesniffer/src/Runner.php(500): PHP_CodeSniffer\Runner->processFile()
#9 /home/superuser/slevomatErrorPOC/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#10 /home/superuser/slevomatErrorPOC/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#11 /home/superuser/slevomatErrorPOC/vendor/bin/phpcs(117): include('...')
#12 {main}
  thrown in /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/ParameterAnnotation.php on line 31
PHP Fatal error:  Uncaught TypeError: SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation::__construct(): Argument #5 ($contentNode) must be of type ?PHPStan\PhpDocParser\Ast\PhpDoc\ParamTagValueNode, PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode given, called in /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php on line 357 and defined in /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/ParameterAnnotation.php:31
Stack trace:
#0 /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php(357): SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation->__construct()
#1 /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(42): SlevomatCodingStandard\Helpers\AnnotationHelper::SlevomatCodingStandard\Helpers\{closure}()
#2 /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffLocalCache.php(31): SlevomatCodingStandard\Helpers\SniffLocalCache::setIfNotCached()
#3 /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php(372): SlevomatCodingStandard\Helpers\SniffLocalCache::getAndSetIfNotCached()
#4 /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Namespaces/UnusedUsesSniff.php(141): SlevomatCodingStandard\Helpers\AnnotationHelper::getAnnotations()
#5 /home/superuser/slevomatErrorPOC/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff->process()
#6 /home/superuser/slevomatErrorPOC/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(130): PHP_CodeSniffer\Files\File->process()
#7 /home/superuser/slevomatErrorPOC/vendor/squizlabs/php_codesniffer/src/Runner.php(628): PHP_CodeSniffer\Files\LocalFile->process()
#8 /home/superuser/slevomatErrorPOC/vendor/squizlabs/php_codesniffer/src/Runner.php(500): PHP_CodeSniffer\Runner->processFile()
#9 /home/superuser/slevomatErrorPOC/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#10 /home/superuser/slevomatErrorPOC/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#11 /home/superuser/slevomatErrorPOC/vendor/bin/phpcs(117): include('...')
#12 {main}
  thrown in /home/superuser/slevomatErrorPOC/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/ParameterAnnotation.php on line 31
```

**Comment by kukulich** [comment]
Just upgrade.
