### ISSUE TITLE
Fatal error in DisallowCommentAfterCodeSniff

### ISSUE THREAD

**Issue by mimmi20** [slevomat/coding-standard#1578]
I got the following fatal error when running phpcbf:

```shell
PHP Fatal error:  Uncaught TypeError: SlevomatCodingStandard\Helpers\FixerHelper::removeBetweenIncluding(): Argument #3 ($endPointer) must be of type int, null given, called in .../vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DisallowCommentAfterCodeSniff.php on line 119 and defined in .../vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/FixerHelper.php:20
Stack trace:
#0 .../vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DisallowCommentAfterCodeSniff.php(119): SlevomatCodingStandard\Helpers\FixerHelper::removeBetweenIncluding()
#1 .../vendor/squizlabs/php_codesniffer/src/Files/File.php(498): SlevomatCodingStandard\Sniffs\Commenting\DisallowCommentAfterCodeSniff->process()
#2 .../vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
#3 .../vendor/squizlabs/php_codesniffer/src/Fixer.php(174): PHP_CodeSniffer\Files\LocalFile->process()
#4 .../vendor/squizlabs/php_codesniffer/src/Reports/Cbf.php(52): PHP_CodeSniffer\Fixer->fixFile()
#5 .../vendor/squizlabs/php_codesniffer/src/Reporter.php(285): PHP_CodeSniffer\Reports\Cbf->generateFileReport()
#6 .../vendor/squizlabs/php_codesniffer/src/Runner.php(658): PHP_CodeSniffer\Reporter->cacheFileReport()
#7 .../vendor/squizlabs/php_codesniffer/src/Runner.php(438): PHP_CodeSniffer\Runner->processFile()
#8 .../vendor/squizlabs/php_codesniffer/src/Runner.php(204): PHP_CodeSniffer\Runner->run()
#9 .../vendor/squizlabs/php_codesniffer/bin/phpcbf(18): PHP_CodeSniffer\Runner->runPHPCBF()
#10 .../bin/phpcbf(120): include('...')
#11 {main}
  thrown in .../vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/FixerHelper.php on line 20
```

The file which causes the error has this content:
```php
<?php
/**
 * This file is part of the jdcgeldde/geld.de package.
 *
 * Copyright (c) 2016-2023, JDC Geld.de GmbH
 * Copyright (c) 2008-2016, Geld.de GmbH
 */

namespace Page\View\Helper;

use Page\Storage\HotlineStorage;
use PHPUnit\Framework\MockObject\Exception;
use PHPUnit\Framework\TestCase;
use Psr\Log\LoggerInterface;

/** phpcs:disable Squiz.NamingConventions.ValidVariableName.MemberNotCamelCaps */
class HotlineTest extends TestCase
{
    /** @throws Exception */
    public function testInvoke(): void
    {
        $hotlineStorage = $this->createMock(HotlineStorage::class);
        $hotlineStorage->expects(static::never())
            ->method('getHotline');

        $logger = $this->createMock(LoggerInterface::class);
        $logger->expects(static::never())
            ->method('info');
        $logger->expects(static::never())
            ->method('warning');
        $logger->expects(static::never())
            ->method('error');

        $object = new Hotline($hotlineStorage, $logger);

        static::assertSame($object, $object());
    }
}

```

When running phpcs the following error is mentinioed:

```shell
FILE: .../module/Page/test/View/Helper/HotlineTest.php
--------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------------------------
 16 | ERROR | [x] Comment after code is disallowed.
    |       |     (SlevomatCodingStandard.Commenting.DisallowCommentAfterCode.DisallowedCommentAfterCode)
--------------------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------------------------------------------------------------------
```

If I change the comment in the errored line (`/**` to `/*`) the error disappears.
```php
<?php
/**
 * This file is part of the jdcgeldde/geld.de package.
 *
 * Copyright (c) 2016-2023, JDC Geld.de GmbH
 * Copyright (c) 2008-2016, Geld.de GmbH
 */

namespace Page\View\Helper;

use Page\Storage\HotlineStorage;
use PHPUnit\Framework\MockObject\Exception;
use PHPUnit\Framework\TestCase;
use Psr\Log\LoggerInterface;

/* phpcs:disable Squiz.NamingConventions.ValidVariableName.MemberNotCamelCaps */
class HotlineTest extends TestCase
{
    /** @throws Exception */
    public function testInvoke(): void
    {
        $hotlineStorage = $this->createMock(HotlineStorage::class);
        $hotlineStorage->expects(static::never())
            ->method('getHotline');

        $logger = $this->createMock(LoggerInterface::class);
        $logger->expects(static::never())
            ->method('info');
        $logger->expects(static::never())
            ->method('warning');
        $logger->expects(static::never())
            ->method('error');

        $object = new Hotline($hotlineStorage, $logger);

        static::assertSame($object, $object());
    }
}

```

**Comment by kukulich** [comment]
In doccomment `/**` you should use `@phpcs:disable`. In standard comment `/*` or `//` you can use `phpcs:disable`

**Comment by mimmi20** [comment]
This may be true, but the error message is misleading as there is no code in that line. And the fatal error should not happen. 

> In doccomment `/**` you should use `@phpcs:disable`.

Is there a rule to check this?

**Comment by kukulich** [comment]
> This may be true, but the error message is misleading

Yes, because with wrong use the parser is confused and broken.

I've found a workaround:  https://github.com/slevomat/coding-standard/commit/ee7410887de86cc1cceb5520983b13a016f7a29f
