### ISSUE TITLE
Possible issue with 8.13.2? Uncaught Error: Call to a member function getNodeStartPointer() on null 

### ISSUE THREAD

**Issue by mikebronner** [slevomat/coding-standard#1600]
Since upgrading to 8.13.2 I am receiving the following error:
```
Fatal error: Uncaught Error: Call to a member function getNodeStartPointer() on null in /github/workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php:115
Stack trace:
#0 /github/workspace/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): SlevomatCodingStandard\Sniffs\Commenting\DocCommentSpacingSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 126)
#1 /github/workspace/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
#2 /github/workspace/vendor/squizlabs/php_codesniffer/src/Runner.php(632): PHP_CodeSniffer\Files\LocalFile->process()
#3 /github/workspace/vendor/squizlabs/php_codesniffer/src/Runner.php(438): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#4 /github/workspace/vendor/squizlabs/php_codesniffer/src/Runner.php(116): PHP_CodeSniffer\Runner->run()
#5 /github/workspace/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
reviewdog: parse error: EOF
#6 /github/workspace/vendor/bin/phpcs(119): include('/github/workspa...')
#7 {main}
  thrown in /github/workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php on line 115
```

**Comment by kukulich** [comment]
@mikebronner Please try to find the specific phpdoc comment that throws this error.

**Comment by mikebronner** [comment]
I believe this is one example, using flag comments to separate sections in a file:
```
    /***************************************************************************
     * Relationships
     */
```

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/daa7ae48cca0e19e320b02c3f3f1176538b6a5c4
