### ISSUE TITLE
Fatal error: Uncaught TypeError: SlevomatCodingStandard\Helpers\IdentificatorHelper::getContent(): Argument #3 ($endPointer) must be of type int, null given

### ISSUE THREAD

**Issue by GBeushausen** [slevomat/coding-standard#1612]
Hi,

i'm developing an application using CakePHP4. When generating a template for viewing a database Table that has a nullable field in it, phpcs quits with a fatal error.

This line is causing the issue:

`<td><?= $pricelist->default_price === null ? '' : $this->Number->format($pricelist->default_price) ?></td>`

This is the error message:
`Fatal error: Uncaught TypeError: SlevomatCodingStandard\Helpers\IdentificatorHelper::getContent(): Argument #3 ($endPointer) must be of type int, null given, called in /Users/info/www/allekto/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/RequireNullCoalesceOperatorSniff.php on line 179 and defined in /Users/info/www/allekto/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/IdentificatorHelper.php:29
Stack trace:
#0 /Users/info/www/allekto/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/RequireNullCoalesceOperatorSniff.php(179): SlevomatCodingStandard\Helpers\IdentificatorHelper::getContent(Object(PHP_CodeSniffer\Files\LocalFile), 358, NULL)
#1 /Users/info/www/allekto/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/RequireNullCoalesceOperatorSniff.php(52): SlevomatCodingStandard\Sniffs\ControlStructures\RequireNullCoalesceOperatorSniff->checkIdenticalOperator(Object(PHP_CodeSniffer\Files\LocalFile), 348)
#2 /Users/info/www/allekto/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): SlevomatCodingStandard\Sniffs\ControlStructures\RequireNullCoalesceOperatorSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 348)
#3 /Users/info/www/allekto/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
#4 /Users/info/www/allekto/vendor/squizlabs/php_codesniffer/src/Runner.php(632): PHP_CodeSniffer\Files\LocalFile->process()
#5 /Users/info/www/allekto/vendor/squizlabs/php_codesniffer/src/Runner.php(438): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#6 /Users/info/www/allekto/vendor/squizlabs/php_codesniffer/src/Runner.php(116): PHP_CodeSniffer\Runner->run()
#7 /Users/info/www/allekto/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
`

If i change the code to this, it wouldn't cause phpcs to fail:

`<td><?= $pricelist->default_price == null ? '' : $this->Number->format($pricelist->default_price) ?></td>`

**Comment by kukulich** [comment]
Our sniffs are not tested for PHP templates. I'm ok to merge PR that will fix it but we will not try to fix it ourself.
