### ISSUE TITLE
Fatal error on namespaced non class PHP file

### ISSUE THREAD

**Issue by dereuromark** [slevomat/coding-standard#1715]
If you run it on
https://github.com/cakephp/cakephp/tree/5.x/src
and the functions.php files in the subfolders,

debugging the ClassHelper yields
- "/data/work/devilbox/data/www/sandbox/vendor/cakephp/cakephp/src/Collection/functions.php"
- "/data/work/devilbox/data/www/sandbox/vendor/cakephp/cakephp/src/I18n/functions.php"

as the not processable files.

https://github.com/cakephp/cakephp/blob/5.x/src/Collection/functions.php
contains a namespaced function, however.

We would expect the sniffer to either just skip those, or gracefully handle them instead of running into a fatal error that is not recoverable and blocks the other sniffs from running on this file.

```
vendor/bin/phpcbf

PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined array key "scope_opener" in /data/work/devilbox/data/www/sandbox/vendor/cakephp/cakephp/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ClassHelper.php on line 64 in /data/work/devilbox/data/www/sandbox/vendor/cakephp/cakephp/vendor/squizlabs/php_codesniffer/src/Runner.php:624
Stack trace:
#0 /data/work/devilbox/data/www/sandbox/vendor/cakephp/cakephp/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ClassHelper.php(64): PHP_CodeSniffer\Runner->handleErrors()
#1 /data/work/devilbox/data/www/sandbox/vendor/cakephp/cakephp/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ClassHelper.php(40): SlevomatCodingStandard\Helpers\ClassHelper::getName()
#2 /data/work/devilbox/data/www/sandbox/vendor/cakephp/cakephp/vendor/cakephp/cakephp-codesniffer/CakePHP/Sniffs/Classes/ReturnTypeHintSniff.php(231): SlevomatCodingStandard\Helpers\ClassHelper::getFullyQualifiedName()
#3 /data/work/devilbox/data/www/sandbox/vendor/cakephp/cakephp/vendor/cakephp/cakephp-codesniffer/CakePHP/Sniffs/Classes/ReturnTypeHintSniff.php(170): CakePHP\Sniffs\Classes\ReturnTypeHintSniff->getClassNameWithNamespace()
#4 /data/work/devilbox/data/www/sandbox/vendor/cakephp/cakephp/vendor/cakephp/cakephp-codesniffer/CakePHP/Sniffs/Classes/ReturnTypeHintSniff.php(54): CakePHP\Sniffs\Classes\ReturnTypeHintSniff->assertNotThisOrStatic()
#5 /data/work/devilbox/data/www/sandbox/vendor/cakephp/cakephp/vendor/squizlabs/php_codesniffer/src/Files/File.php(519): CakePHP\Sniffs\Classes\ReturnTypeHintSniff->process()
#6 /data/work/devilbox/data/www/sandbox/vendor/cakephp/cakephp/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
#7 /data/work/devilbox/data/www/sandbox/vendor/cakephp/cakephp/vendor/squizlabs/php_codesniffer/src/Fixer.php(175): PHP_CodeSniffer\Files\LocalFile->process()
```

**Comment by kukulich** [comment]
I'm not able to reproduce it. I expect there's a problem in `CakePHP/Sniffs/Classes/ReturnTypeHintSniff`
