### ISSUE TITLE
TraitUseSpacing encounters Undefined index: scope_closer when renamed function

### ISSUE THREAD

**Issue by Levivb** [slevomat/coding-standard#403]
Hey,

In the masterbranch the fixer of the sniff `TraitUseSpacing` runs into an `Undefined index: scope_closer` `RuntimeException` when  coming across a use statement with renamed function:

The code causing the error:
```php
class MyClass
{
    use Trait1 {
        Trait1::hook as Trait1Hook;
    }
    use Trait2;
    ...
}
```

The full stacktrace:
```bash
$ composer fix-style
> vendor/bin/phpcbf --standard=phpcs.xml
..................................
Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_closer in /home/vagrant/Code/myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 156 in /home/vagrant/Code/myproject/vendor/squizlabs/php_codesniffer/src/Runner.php on line 562

PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_closer in /home/vagrant/Code/myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 156 in /home/vagrant/Code/myproject/vendor/squizlabs/php_codesniffer/src/Runner.php on line 562

Call Stack:
0.0005     390672   1. {main}() /home/vagrant/Code/myproject/vendor/squizlabs/php_codesniffer/bin/phpcbf:0
0.0708    7270000   2. PHP_CodeSniffer\Runner->runPHPCBF() /home/vagrant/Code/myproject/vendor/squizlabs/php_codesniffer/bin/phpcbf:18
0.2501   11734784   3. PHP_CodeSniffer\Runner->run() /home/vagrant/Code/myproject/vendor/squizlabs/php_codesniffer/src/Runner.php:193
1.7415   13945496   4. PHP_CodeSniffer\Runner->processFile() /home/vagrant/Code/myproject/vendor/squizlabs/php_codesniffer/src/Runner.php:394
2.0292   16181864   5. PHP_CodeSniffer\Reporter->cacheFileReport() /home/vagrant/Code/myproject/vendor/squizlabs/php_codesniffer/src/Runner.php:611
2.0293   16200392   6. PHP_CodeSniffer\Reports\Cbf->generateFileReport() /home/vagrant/Code/myproject/vendor/squizlabs/php_codesniffer/src/Reporter.php:284
2.0293   16200392   7. PHP_CodeSniffer\Fixer->fixFile() /home/vagrant/Code/myproject/vendor/squizlabs/php_codesniffer/src/Reports/Cbf.php:48
2.3081   16224496   8. PHP_CodeSniffer\Files\LocalFile->process() /home/vagrant/Code/myproject/vendor/squizlabs/php_codesniffer/src/Fixer.php:174
2.3081   16224496   9. PHP_CodeSniffer\Files\LocalFile->process() /home/vagrant/Code/myproject/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php:91
2.3719   16255928  10. SlevomatCodingStandard\Sniffs\Exceptions\ReferenceThrowableOnlySniff->process() /home/vagrant/Code/myproject/vendor/squizlabs/php_codesniffer/src/Files/File.php:497
2.3719   16256248  11. SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatements() /home/vagrant/Code/myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Exceptions/ReferenceThrowableOnlySniff.php:49
2.3719   16256376  12. SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatementPointers() /home/vagrant/Code/myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php:108
2.3721   16258240  13. PHP_CodeSniffer\Runner->handleErrors() /home/vagrant/Code/myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php:156

PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_closer in /home/vagrant/Code/myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 156 in /home/vagrant/Code/myproject/vendor/squizlabs/php_codesniffer/src/Runner.php:562
Stack trace:
#0 /home/vagrant/Code/myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php(156): PHP_CodeSniffer\Runner->handleErrors(8, 'Undefined index...', '/home/vagrant/C...', 156, Array)
#1 /home/vagrant/Code/myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php(108): SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatementPointers(Object(PHP_CodeSniffer\Files\LocalFile), 0)
#2 /home/vagrant/Code/myproject/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Exceptions/ReferenceThrowableOnlySniff.php(49): SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatements(Object(PHP_CodeSniffer\Files\L in /home/vagrant/Code/myproject/vendor/squizlabs/php_codesniffer/src/Runner.php on line 562

Script vendor/bin/phpcbf --standard=phpcs.xml handling the fix-style event returned with error code 255
```

I'm not sure if it's an easy fix. But you seem to know what your doing with all these great sniffs!
Let me know if you need any more information and thinks it's worth fixing :)

**Comment by Levivb** [comment]
Btw, in this case swapping the usages like so:
```php
    use Trait2;
    use Trait1 {
        Trait1::hook as Trait1Hook;
    }
```
obviously prevents the failure. But it'd be harder in such a case:
```php
    use Trait2 {
        Trait2::hook as Trait2Hook;
    }
    use Trait1 {
        Trait1::hook as Trait1Hook;
    }
    use Trait 3;
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/4bd7f7bffde901cc43e6837b249a6a5857b2bc27.
