### ISSUE TITLE
Fatal error in OptimizedFunctionsWithoutUnpackingSniff

### ISSUE THREAD

**Issue by EvgenyOrekhov** [slevomat/coding-standard#485]
```text
Fatal error: Uncaught TypeError: Argument 2 passed to SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatements() must be of the type integer, null given, called in /app/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/PHP/OptimizedFunctionsWithoutUnpackingSniff.php on line 96 and defined in /app/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php:93
Stack trace:
#0 /app/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/PHP/OptimizedFunctionsWithoutUnpackingSniff.php(96): SlevomatCodingStandard\Helpers\UseStatementHelper::getUseStatements(Object(PHP_CodeSniffer\Files\LocalFile), NULL)
#1 /app/vendor/squizlabs/php_codesniffer/src/Files/File.php(497): SlevomatCodingStandard\Sniffs\PHP\OptimizedFunctionsWithoutUnpackingSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 5)
#2 /app/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(91): PHP_CodeSniffer\Files\File->process()
#3 /app/vendor/squizlabs/php_codesniffer/src/Runner.php(585): PHP_CodeSniff in /app/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/UseStatementHelper.php on line 93
```

Slevomat Coding Standard version: 4.8.0
PHP_CodeSniffer version: 3.3.1
PHP version: 7.2.8

**Comment by kukulich** [comment]
@EvgenyOrekhov Impossible to fix without the code

**Comment by EvgenyOrekhov** [comment]
@kukulich Here you go!

```php
<?= \Yii::t('common', 'The list is empty');

```

**Comment by kukulich** [comment]
I'm sorry, `<?=` is not supported in our sniffs. I would accept PR to support this but I will not invest my time.
