### ISSUE TITLE
Crash in DocCommentSpacingSniff (Call to a member function getEndPointer() on array)

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#492]
Reproducible crash on the following class from BetterReflection:
https://github.com/Roave/BetterReflection/blob/ffe74cae76a35d09cdc913fda5390a6317d170f6/src/Reflection/ReflectionClass.php

Stack trace:
```
$ vendor/bin/phpcs src/Reflection/ReflectionClass.php --sniffs=SlevomatCodingStandard.Commenting.DocCommentSpacing -v
Registering sniffs in the Roave/BetterReflection coding standard standard... DONE (1 sniffs registered)
Creating file list... DONE (1 files in queue)
Changing into directory src/Reflection
Processing ReflectionClass.php [PHP => 9156 tokens in 1412 lines]... PHP Fatal error:  Uncaught Error: Call to a member function getEndPointer() on array in vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php:389
Stack trace:
#0 vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php(360): SlevomatCodingStandard\Sniffs\Commenting\DocCommentSpacingSniff->checkLinesBetweenAnnotationsGroups(Object(PHP_CodeSniffer\Files\LocalFile), 6819, Array)
#1 vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php(142): SlevomatCodingStandard\Sniffs\Commenting\DocCommentSpacingSniff->checkAnnotationsGroups(Object(PHP_CodeSniffer\Files\LocalFile), 6819, Array)
#2 vendor/squizlabs/php_codesniffer/src/Files/File.php(497): SlevomatCodingStandard\Sniffs\Commenting\DocCommentSpacingSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 6819)
#3 /www/roave/betterreflection in vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php on line 389

Fatal error: Uncaught Error: Call to a member function getEndPointer() on array in vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php:389
Stack trace:
#0 vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php(360): SlevomatCodingStandard\Sniffs\Commenting\DocCommentSpacingSniff->checkLinesBetweenAnnotationsGroups(Object(PHP_CodeSniffer\Files\LocalFile), 6819, Array)
#1 vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php(142): SlevomatCodingStandard\Sniffs\Commenting\DocCommentSpacingSniff->checkAnnotationsGroups(Object(PHP_CodeSniffer\Files\LocalFile), 6819, Array)
#2 vendor/squizlabs/php_codesniffer/src/Files/File.php(497): SlevomatCodingStandard\Sniffs\Commenting\DocCommentSpacingSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 6819)
#3 /www/roave/betterreflection in vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php on line 389
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/fb3ecc04ea12aefcae4c64994132c26899b8b9a2
