### ISSUE TITLE
DocCommentSpacing: Fixer fatal error - max(): array must contain at least one element

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#499]
```
Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: max(): Array must contain at least one element in /www/doctrine/cache/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php on line 502 in /www/doctrine/cache/vendor/squizlabs/php_codesniffer/src/Runner.php:562
Stack trace:
#0 [internal function]: PHP_CodeSniffer\Runner->handleErrors(2, 'max(): Array mu...', '/www/doctrine/c...', 502, Array)
#1 /www/doctrine/cache/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php(502): max(Array)
#2 /www/doctrine/cache/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php(359): SlevomatCodingStandard\Sniffs\Commenting\DocCommentSpacingSniff->checkAnnotationsGroupsOrder(Object(PHP_CodeSniffer\Files\LocalFile), 1636, Array, Array)
#3 /www/doctrine/cache/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Commenting/DocCommentSpacingSniff.php(142): SlevomatCodingStandard\Sniff in /www/doctrine/cache/vendor/squizlabs/php_codesniffer/src/Runner.php on line 562
```

Seems to be related to [this docComment](https://github.com/doctrine/cache/blob/37a0f58797616871368e860392878e09526341d1/tests/Doctrine/Tests/Common/Cache/FileCacheTest.php#L228-L232) - after removing it, the file gets fixed, but after re-adding it the sniff stays silent (wrong spacing should be reported).

**Comment by kukulich** [comment]
I will probably hate this sniff very early :)

Internal error fixed in https://github.com/slevomat/coding-standard/commit/9044c82b6819103997dce21fd15d0ba5b5c91522

**Comment by Majkl578** [comment]
I really like this sniff though! But you may hate the fixer. :stuck_out_tongue:

**Comment by kukulich** [comment]
Second error fixed in https://github.com/slevomat/coding-standard/commit/122e670fe337a833e45fa01ef2c4706d54b739bd
