### ISSUE TITLE
FatalError RequireExplicitAssertionSniff 

### ISSUE THREAD

**Issue by henri9813** [slevomat/coding-standard#715]
Hello,

 i use travis-ci for my project but i have a problem.
Here is my PR: https://github.com/henri9813/HDGamePanel/pull/2

And here an example of fail.
https://travis-ci.com/henri9813/HDGamePanel/jobs/209762473

```
		Process token 83: T_DOC_COMMENT_OPEN_TAG => /**
			Processing SlevomatCodingStandard\Sniffs\PHP\RequireExplicitAssertionSniff... PHP Fatal error:  Uncaught Error: Call to undefined method SlevomatCodingStandard\Helpers\TokenHelper::findFirstNonWhitespaceOnNextLine() in /tmp/slcs/SlevomatCodingStandard/Sniffs/PHP/RequireExplicitAssertionSniff.php:63
Stack trace:
#0 /home/travis/build/henri9813/HDGamePanel/app/vendor/squizlabs/php_codesniffer/src/Files/File.php(489): SlevomatCodingStandard\Sniffs\PHP\RequireExplicitAssertionSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 83)
#1 /home/travis/build/henri9813/HDGamePanel/app/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(91): PHP_CodeSniffer\Files\File->process()
#2 /home/travis/build/henri9813/HDGamePanel/app/vendor/squizlabs/php_codesniffer/src/Runner.php(630): PHP_CodeSniffer\Files\LocalFile->process()
#3 /home/travis/build/henri9813/HDGamePanel/app/vendor/squizlabs/php_codesniffer/src/Runner.php(434): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#4 /home/travis/build/henri9813/HDGamePanel/app/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeS in /tmp/slcs/SlevomatCodingStandard/Sniffs/PHP/RequireExplicitAssertionSniff.php on line 63
Fatal error: Uncaught Error: Call to undefined method SlevomatCodingStandard\Helpers\TokenHelper::findFirstNonWhitespaceOnNextLine() in /tmp/slcs/SlevomatCodingStandard/Sniffs/PHP/RequireExplicitAssertionSniff.php on line 63
Error: Call to undefined method SlevomatCodingStandard\Helpers\TokenHelper::findFirstNonWhitespaceOnNextLine() in /tmp/slcs/SlevomatCodingStandard/Sniffs/PHP/RequireExplicitAssertionSniff.php on line 63
Call Stack:
    0.0001     410840   1. {main}() /home/travis/build/henri9813/HDGamePanel/app/vendor/squizlabs/php_codesniffer/bin/phpcs:0
    0.0039     812320   2. PHP_CodeSniffer\Runner->runPHPCS() /home/travis/build/henri9813/HDGamePanel/app/vendor/squizlabs/php_codesniffer/bin/phpcs:18
    0.1598    6899952   3. PHP_CodeSniffer\Runner->run() /home/travis/build/henri9813/HDGamePanel/app/vendor/squizlabs/php_codesniffer/src/Runner.php:114
    0.1684    7787160   4. PHP_CodeSniffer\Runner->processFile() /home/travis/build/henri9813/HDGamePanel/app/vendor/squizlabs/php_codesniffer/src/Runner.php:434
    0.1684    7787160   5. PHP_CodeSniffer\Files\LocalFile->process() /home/travis/build/henri9813/HDGamePanel/app/vendor/squizlabs/php_codesniffer/src/Runner.php:630
    0.1684    7787160   6. PHP_CodeSniffer\Files\LocalFile->process() /home/travis/build/henri9813/HDGamePanel/app/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php:91
    0.2293    8306272   7. SlevomatCodingStandard\Sniffs\PHP\RequireExplicitAssertionSniff->process() /home/travis/build/henri9813/HDGamePanel/app/vendor/squizlabs/php_codesniffer/src/Files/File.php:489
make: *** [cs] Error 255
The command "make cs" exited with 2.
```

I tried with php 7.2 and php 7.3

I made a mistake somewhere ? 

Thanks you

Best regards,
Henri Devigne

**Comment by henri9813** [comment]
I use 5.0.4 and it works,

I have this problem using branch Master

**Comment by kukulich** [comment]
Please post the code that throws this error.
