### ISSUE TITLE
RequireExplicitAssertionSniff fails if variable has invalid 

### ISSUE THREAD

**Issue by petrhejna** [slevomat/coding-standard#785]
Where: `master`

The problem is that in `RequireExplicitAssertionSniff:81` the code 
```php
                        if ($variableAnnotation->getVariableName() === null) {
				continue;
			}
```

May fail beause `getVariableName()` throws error if there is invalid `@var` annotation

```
PHP Fatal error:  Uncaught LogicException: Invalid @var annotation. in /xxx/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/VariableAnnotation.php:70
Stack trace:
#0 /xxxx/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/PHP/RequireExplicitAssertionSniff.php(81): SlevomatCodingStandard\Helpers\Annotation\VariableAnnotation->getVariableName()
#1 /xxxx/vendor/squizlabs/php_codesniffer/src/Files/File.php(496): SlevomatCodingStandard\Sniffs\PHP\RequireExplicitAssertionSniff->process()
#2 /xxxx/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(91): PHP_CodeSniffer\Files\File->process()
#3 /xxxx/vendor/squizlabs/php_codesniffer/src/Fixer.php(174): PHP_CodeSniffer\Files\LocalFile->process()
#4 /xxxx/vendor/squizlabs/ in /xxxx/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/VariableAnnotation.php on line 70
```

**Comment by kukulich** [comment]
@petrhejna Please post the code that throws this error.

**Comment by petrhejna** [comment]
```php
    /**
     * @param BE_Form_Filter $form
     * @return array
     */
    private function getFormErrors(BE_Form_Filter $form)
    {
        $errors = [];

        foreach ($form->getForm() as $name => $field) {
            /** @var $field Core_Form_Field_Abstract */
            if ($field->getErrors()) {
                $errors[$name] = current($field->getErrors());
            }
        }

        return $errors;
    }
```

**Comment by petrhejna** [comment]
The `/** @var $field Core_Form_Field_Abstract */` is invalid

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/dc5a270645e7b48dd6e18005fad7c439161799bd
