### ISSUE TITLE
PHP Fatal error:  Uncaught Exception: "if" without curly braces is not supported 

### ISSUE THREAD

**Issue by Awilum** [slevomat/coding-standard#819]
```
MacBook-Pro-Sergey:flextype awilum$ vendor/bin/phpcbf --standard=Doctrine flextype

PHP Fatal error:  Uncaught Exception: "if" without curly braces is not supported. in /Applications/MAMP/htdocs/flextype/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/AbstractControlStructureSpacingSniff.php:275
Stack trace:
#0 /Applications/MAMP/htdocs/flextype/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/AbstractControlStructureSpacingSniff.php(211): SlevomatCodingStandard\Sniffs\ControlStructures\AbstractControlStructureSpacingSniff->findControlStructureEnd(Object(PHP_CodeSniffer\Files\LocalFile), 636)
#1 /Applications/MAMP/htdocs/flextype/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/AbstractControlStructureSpacingSniff.php(90): SlevomatCodingStandard\Sniffs\ControlStructures\AbstractControlStructureSpacingSniff->checkLinesAfter(Object(PHP_CodeSniffer\Files\LocalFile), 636)
#2 /Applications/MAMP/htdocs/flextype/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/BlockControlStructureSpacingSniff in /Applications/MAMP/htdocs/flextype/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/AbstractControlStructureSpacingSniff.php on line 275

Fatal error: Uncaught Exception: "if" without curly braces is not supported. in /Applications/MAMP/htdocs/flextype/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/AbstractControlStructureSpacingSniff.php:275
Stack trace:
#0 /Applications/MAMP/htdocs/flextype/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/AbstractControlStructureSpacingSniff.php(211): SlevomatCodingStandard\Sniffs\ControlStructures\AbstractControlStructureSpacingSniff->findControlStructureEnd(Object(PHP_CodeSniffer\Files\LocalFile), 636)
#1 /Applications/MAMP/htdocs/flextype/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/AbstractControlStructureSpacingSniff.php(90): SlevomatCodingStandard\Sniffs\ControlStructures\AbstractControlStructureSpacingSniff->checkLinesAfter(Object(PHP_CodeSniffer\Files\LocalFile), 636)
#2 /Applications/MAMP/htdocs/flextype/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/BlockControlStructureSpacingSniff in /Applications/MAMP/htdocs/flextype/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/ControlStructures/AbstractControlStructureSpacingSniff.php on line 275
```

from my composer.lock 

```
"name": "doctrine/coding-standard",
"version": "7.0.2",
...
    "require": {
        "dealerdirect/phpcodesniffer-composer-installer": "^0.5.0",
        "php": "^7.2",
        "slevomat/coding-standard": "^6.0",
        "squizlabs/php_codesniffer": "^3.5.3"
    },
...
"name": "slevomat/coding-standard",
"version": "6.0.5",
```

**Comment by kukulich** [comment]
See the reported exception.

It's intended.
