### ISSUE TITLE
Fatal error while using SlevomatCodingStandard.Classes.PropertySpacing

### ISSUE THREAD

**Issue by dshemin** [slevomat/coding-standard#916]
Hi,
Thanks for this great coding standard!
Today I ran into an error when I try to use `SlevomatCodingStandard.Classes.PropertySpacing` sniffer.

PHP version: 
```
PHP 7.3.9 (cli) (built: Sep 14 2019 18:07:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9, Copyright (c) 1999-2018, by Zend Technologies
```
slevomat/coding-standard version: 6.1.5

**Output:**
```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff::isNextMemberValid() must be of the type int, null given, called in /Users/dmitriysemin/Workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/AbstractPropertyAndConstantSpacing.php on line 67 and defined in /Users/dmitriysemin/Workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/PropertySpacingSniff.php:45
Stack trace:
#0 /Users/dmitriysemin/Workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/AbstractPropertyAndConstantSpacing.php(67): SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff->isNextMemberValid(Object(PHP_CodeSniffer\Files\LocalFile), NULL)
#1 /Users/dmitriysemin/Workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/PropertySpacingSniff.php(42): SlevomatCodingStandard\Sniffs\Classes\AbstractPropert in /Users/dmitriysemin/Workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/PropertySpacingSniff.php on line 45

Fatal error: Uncaught TypeError: Argument 2 passed to SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff::isNextMemberValid() must be of the type int, null given, called in /Users/dmitriysemin/Workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/AbstractPropertyAndConstantSpacing.php on line 67 and defined in /Users/dmitriysemin/Workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/PropertySpacingSniff.php:45
Stack trace:
#0 /Users/dmitriysemin/Workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/AbstractPropertyAndConstantSpacing.php(67): SlevomatCodingStandard\Sniffs\Classes\PropertySpacingSniff->isNextMemberValid(Object(PHP_CodeSniffer\Files\LocalFile), NULL)
#1 /Users/dmitriysemin/Workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/PropertySpacingSniff.php(42): SlevomatCodingStandard\Sniffs\Classes\AbstractPropert in /Users/dmitriysemin/Workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/PropertySpacingSniff.php on line 45
```

**Comment by kukulich** [comment]
@dshemin Please post code that throws this error.

**Comment by dshemin** [comment]
For now, I found one possible file with next content:
```php
<?php

namespace Tests\Unit\App\Enums;

use App\Enums\Enum;
use Tests\TestCase;

/**
 * Class EnumTest
 *
 * @package Tests\Unit\App\Enums
 */
class EnumTest extends TestCase
{

    public function testToArray(): void
    {
        $enum = new class('bar') extends Enum {
            protected const EXCLUDED_CONSTANTS = [ 'FOO', 'FIZZ' ];

            public const FOO = 'foo';
            public const BAR = 'bar';
            public const FIZZ = 'fizz';
            public const BUZZ = 'buzz';
        };

        $class = get_class($enum);

        $this->assertEquals([
            'BAR' => 'bar',
            'BUZZ' => 'buzz',
        ], $class::toArray());
    }

    public function testStringValues(): void
    {
        $enum = new class('bar') extends Enum {
            protected const EXCLUDED_CONSTANTS = [ 'FOO', 'FIZZ' ];

            public const FOO = 'foo';
            public const BAR = 'bar';
            public const FIZZ = 'fizz';
            public const BUZZ = 'buzz';
        };

        /** @var Enum $class */
        $class = get_class($enum);

        $this->assertEquals([ 'bar', 'buzz' ], $class::stringValues());
    }
}
```

Looks like anonymous classes are the reason for the failure 'cause exception is gone when I extract them into a separate class like this:

```php
<?php
// Copyright 1999-2020. Plesk International GmbH. All rights reserved.

namespace Tests\Unit\App\Enums;

use App\Enums\Enum;
use Tests\TestCase;

/**
 * Class EnumTest
 *
 * @package Tests\Unit\App\Enums
 */
class EnumTest extends TestCase
{

    public function testToArray(): void
    {
        $enum = new TestEnum('bar');

        $class = get_class($enum);

        $this->assertEquals([
            'BAR' => 'bar',
            'BUZZ' => 'buzz',
        ], $class::toArray());
    }

    public function testStringValues(): void
    {
        $enum = new TestEnum('bar');

        /** @var Enum $class */
        $class = get_class($enum);

        $this->assertEquals([ 'bar', 'buzz' ], $class::stringValues());
    }
}

class TestEnum extends Enum {
    protected const EXCLUDED_CONSTANTS = [ 'FOO', 'FIZZ' ];

    public const FOO = 'foo';
    public const BAR = 'bar';
    public const FIZZ = 'fizz';
    public const BUZZ = 'buzz';
}
```

**Comment by kukulich** [comment]
Fixed in https://github.com/slevomat/coding-standard/commit/4a4785a821c849d0edf6e1ab303bf3f3626b4c37
