### ISSUE TITLE
ParameterTypeHintSniff causing fatal undefined index.

### ISSUE THREAD

**Issue by bendavies** [slevomat/coding-standard#943]
Hi,

This is with:
```
slevomat/coding-standard                       6.1.5
squizlabs/php_codesniffer                      3.5.4
```
Currently trying to fine out which file/annotation is causing this in my project.
Is there an easy way to find out?

Thanks!

```
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index:  in /project/vendor/squizlabs/php_codesniffer/src/Fixer.php on line 529 in /project/vendor/squizlabs/php_codesniffer/src/Runner.php:606
Stack trace:
#0 /project/vendor/squizlabs/php_codesniffer/src/Fixer.php(529): PHP_CodeSniffer\Runner->handleErrors(8, 'Undefined index...', '/Users/ben/Code...', 529, Array)
#1 /project/vendor/squizlabs/php_codesniffer/src/Fixer.php(390): PHP_CodeSniffer\Fixer->replaceToken('', '')
#2 /project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/TypeHints/ParameterTypeHintSniff.php(377): PHP_CodeSniffer\Fixer->endChangeset()
#3 /project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/TypeHints/ParameterTypeHintSniff.php(98): SlevomatCodingStandard\Sniffs\TypeHints\ParameterTypeHintSniff->checkUselessAnnotations(Object( in /project/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606
```

**Comment by kukulich** [comment]
@bendavies PHPCS has `verbose` option.

**Comment by bendavies** [comment]
I've identified the file, trying to track down the line now.

**Comment by bendavies** [comment]
Here's the last few lines

```
	=> Changeset started by SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:364
		Q: SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:383 replaced token 2109 (T_NS_SEPARATOR on line 886) "\" => "sprintf"
		Q: SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:387 replaced token 2110 (T_STRING on line 886) "Safe" => ""
		Q: SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:387 replaced token 2111 (T_NS_SEPARATOR on line 886) "\" => ""
		Q: SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:387 replaced token 2112 (T_STRING on line 886) "sprintf" => ""
		Q: SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:396 replaced token 162 (T_SEMICOLON on line 19) "\n" => "\n\n"
		Q: SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:397 replaced token 162 (T_SEMICOLON on line 19) "\n" => "\nuse·function·Safe\sprintf;\n"
		A: SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:400 replaced token 2109 (T_NS_SEPARATOR on line 886) "\" => "sprintf"
		A: SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:400 replaced token 2110 (T_STRING on line 886) "Safe" => ""
		A: SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:400 replaced token 2111 (T_NS_SEPARATOR on line 886) "\" => ""
		A: SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:400 replaced token 2112 (T_STRING on line 886) "sprintf" => ""
		* token 162 has already been modified, skipping *
		R: SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:400 reverted token 2109 (T_NS_SEPARATOR on line 886) "sprintf" => "\"
		R: SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:400 reverted token 2110 (T_STRING on line 886) "" => "Safe"
		R: SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:400 reverted token 2111 (T_NS_SEPARATOR on line 886) "" => "\"
		R: SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly:400 reverted token 2112 (T_STRING on line 886) "(" => "sprintf("
	=> Changeset failed to apply
	=> Changeset started by SlevomatCodingStandard.TypeHints.ReturnTypeHint:373
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index:  in /project/vendor/squizlabs/php_codesniffer/src/Fixer.php on line 502 in /project/vendor/squizlabs/php_codesniffer/src/Runner.php:606
Stack trace:
#0 /project/vendor/squizlabs/php_codesniffer/src/Fixer.php(502): PHP_CodeSniffer\Runner->handleErrors(8, 'Undefined index...', '/Users/ben/Code...', 502, Array)
#1 /project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/TypeHints/ReturnTypeHintSniff.php(375): PHP_CodeSniffer\Fixer->replaceToken(NULL, '')
#2 /project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/TypeHints/ReturnTypeHintSniff.php(98): SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff->checkFunctionUselessAnnotation(Object(PHP_CodeSniffer\Files\LocalFile), 1295, Object(SlevomatCodingStandard\Helpers\ReturnTypeHint), Object(SlevomatCodingStandard\Helper in /project/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606
```

**Comment by kukulich** [comment]
@bendavies I need you code that throws the error so I can prepare unit test and fix it.

**Comment by bendavies** [comment]
yep no problem, trying to track it down.

**Comment by bendavies** [comment]
ok, it's erroring on a single line return docblock like this:
```php
/** @return Route */
protected function getRoute(array $configuration)
{
...
}
```

I tried on master and it seems fixed. can close i think?

**Comment by kukulich** [comment]
Perfect, it's probably duplicate to https://github.com/slevomat/coding-standard/pull/931

**Comment by bendavies** [comment]
Great, Thanks!
