### ISSUE TITLE
Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_opener

### ISSUE THREAD

**Issue by bendavies** [slevomat/coding-standard#944]
Hi,

This on HEAD of master.

Here's a stack trace:

```
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_opener in /project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ClassHelper.php on line 56 in /project/vendor/squizlabs/php_codesniffer/src/Runner.php:606
Stack trace:
#0 /project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ClassHelper.php(56): PHP_CodeSniffer\Runner->handleErrors(8, 'Undefined index...', '/Users/ben/Code...', 56, Array)
#1 /project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ClassHelper.php(74): SlevomatCodingStandard\Helpers\ClassHelper::getName(Object(PHP_CodeSniffer\Files\LocalFile), 70)
#2 /project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Namespaces/ReferenceUsedNamesOnlySniff.php(152): SlevomatCodingStandard\Helpers\ClassHelper::getAllNames(Object(PHP_CodeSniffer\Files\LocalFile))
#3 /Users/ben/Cod in /project/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606

Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_opener in /project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ClassHelper.php on line 56 in /project/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606

PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_opener in /project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ClassHelper.php on line 56 in /project/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606

Call Stack:
    0.0095     405056   1. {main}() /project/vendor/squizlabs/php_codesniffer/bin/phpcbf:0
    0.1716    8194176   2. PHP_CodeSniffer\Runner->runPHPCBF() /project/vendor/squizlabs/php_codesniffer/bin/phpcbf:18
    0.3835   14681992   3. PHP_CodeSniffer\Runner->run() /project/vendor/squizlabs/php_codesniffer/src/Runner.php:200
    0.3906   15222080   4. PHP_CodeSniffer\Runner->processFile(???) /project/vendor/squizlabs/php_codesniffer/src/Runner.php:434
   14.7144   15696488   5. PHP_CodeSniffer\Reporter->cacheFileReport(???, ???) /project/vendor/squizlabs/php_codesniffer/src/Runner.php:656
   14.7146   15715264   6. PHP_CodeSniffer\Reports\Cbf->generateFileReport(???, ???, ???, ???) /project/vendor/squizlabs/php_codesniffer/src/Reporter.php:285
   14.7146   15715264   7. PHP_CodeSniffer\Fixer->fixFile() /project/vendor/squizlabs/php_codesniffer/src/Reports/Cbf.php:49
   14.7440   15741872   8. PHP_CodeSniffer\Files\LocalFile->process() /project/vendor/squizlabs/php_codesniffer/src/Fixer.php:174
   14.7440   15741872   9. PHP_CodeSniffer\Files\LocalFile->process() /project/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php:91
   14.7825   15928824  10. SlevomatCodingStandard\Sniffs\Namespaces\ReferenceUsedNamesOnlySniff->process(???, ???) /project/vendor/squizlabs/php_codesniffer/src/Files/File.php:496
   14.7837   15933264  11. SlevomatCodingStandard\Helpers\ClassHelper::getAllNames(???) /project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Namespaces/ReferenceUsedNamesOnlySniff.php:152
   14.7838   15933264  12. SlevomatCodingStandard\Helpers\ClassHelper::getName(???, ???) /project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ClassHelper.php:74
   15.7831   15934752  13. PHP_CodeSniffer\Runner->handleErrors(???, ???, ???, ???, ???) /project/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/ClassHelper.php:56
```

There's the code
```php
<?php

declare(strict_types=1);

namespace Abacus\Bundle\VoidBundle\Factory;

use Abacus\Bundle\AimPaymentBundle\Entity\AimPaymentReceipt;
use Abacus\Bundle\ReceiptBundle\Entity\Receipt;
use ApiPlatform\Core\Exception\InvalidArgumentException;
use function Functional\some;

class NsfForReceiptFactory extends ReceiptVoidingFactory
{
    protected function assertVoidable(Receipt $receipt): void
    {
        if ($receipt->isVoided()) {
            throw new InvalidArgumentException('Receipt has already been voided.');
        }

        if (!$receipt->isDeposited()) {
            throw new InvalidArgumentException('Receipt has not been deposited.');
        }

        if (some($receipt->getAimPayments(), static fn (AimPaymentReceipt $payment): bool => !$payment->getPayment()->isVoided())) {
            throw new InvalidArgumentException('Receipt has been refunded.');
        }

        if (null !== $receipt->getBankReconciliation()) {
            throw new InvalidArgumentException('Receipt has been reconciled.');
        }
    }

    protected function setState(Receipt $receipt): void
    {
        $receipt->setNsfed(true);
    }
}
```

**Comment by kukulich** [comment]
@bendavies Could you try to change arrow function to closure?

**Comment by bendavies** [comment]
yep, it's fine then. that's the issue.

**Comment by kukulich** [comment]
So it should be fixed in PHPCS master: https://github.com/squizlabs/PHP_CodeSniffer/issues/2867

**Comment by bendavies** [comment]
nice thanks!
