### ISSUE TITLE
ConstantSpacingSniff crashes on global const

### ISSUE THREAD

**Issue by ondrejmirtes** [slevomat/coding-standard#961]
Example code:

```php
<?php

const WIDTH_MAX = 2016;
const WIDTH_MIN = 50;
const HEIGHT_MAX = 2000;
const HEIGHT_MIN = 50;
```

Stack trace:

```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to SlevomatCodingStandard\Sniffs\Classes\ConstantSpacingSniff::isNextMemberValid() must be of the type int, null given, called in /Users/ondrej/Development/slevomat-cdn-scripts/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/AbstractPropertyAndConstantSpacing.php on line 68 and defined in /Users/ondrej/Development/slevomat-cdn-scripts/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/ConstantSpacingSniff.php:25
Stack trace:
#0 /Users/ondrej/Development/slevomat-cdn-scripts/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/AbstractPropertyAndConstantSpacing.php(68): SlevomatCodingStandard\Sniffs\Classes\ConstantSpacingSniff->isNextMemberValid(Object(PHP_CodeSniffer\Files\LocalFile), NULL)
#1 /Users/ondrej/Development/slevomat-cdn-scripts/vendor/squizlabs/php_codesniffer/src/Files/File.php(496): SlevomatCodingStandard\Sniffs\Classes\AbstractPropertyAndConstantSpacing->process(Object(PHP_CodeSniffer\Files\LocalFil in /Users/ondrej/Development/slevomat-cdn-scripts/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/ConstantSpacingSniff.php on line 25

Fatal error: Uncaught TypeError: Argument 2 passed to SlevomatCodingStandard\Sniffs\Classes\ConstantSpacingSniff::isNextMemberValid() must be of the type int, null given, called in /Users/ondrej/Development/slevomat-cdn-scripts/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/AbstractPropertyAndConstantSpacing.php on line 68 and defined in /Users/ondrej/Development/slevomat-cdn-scripts/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/ConstantSpacingSniff.php on line 25

TypeError: Argument 2 passed to SlevomatCodingStandard\Sniffs\Classes\ConstantSpacingSniff::isNextMemberValid() must be of the type int, null given, called in /Users/ondrej/Development/slevomat-cdn-scripts/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/AbstractPropertyAndConstantSpacing.php on line 68 in /Users/ondrej/Development/slevomat-cdn-scripts/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/ConstantSpacingSniff.php on line 25

Call Stack:
    0.0003     395992   1. {main}() /Users/ondrej/Development/slevomat-cdn-scripts/vendor/squizlabs/php_codesniffer/bin/phpcs:0
    0.0057    1145408   2. PHP_CodeSniffer\Runner->runPHPCS() /Users/ondrej/Development/slevomat-cdn-scripts/vendor/squizlabs/php_codesniffer/bin/phpcs:18
    0.1514    8479680   3. PHP_CodeSniffer\Runner->run() /Users/ondrej/Development/slevomat-cdn-scripts/vendor/squizlabs/php_codesniffer/src/Runner.php:114
    1.8403   10602688   4. PHP_CodeSniffer\Runner->processFile() /Users/ondrej/Development/slevomat-cdn-scripts/vendor/squizlabs/php_codesniffer/src/Runner.php:434
    1.8403   10602688   5. PHP_CodeSniffer\Files\LocalFile->process() /Users/ondrej/Development/slevomat-cdn-scripts/vendor/squizlabs/php_codesniffer/src/Runner.php:630
    1.8403   10602688   6. PHP_CodeSniffer\Files\LocalFile->process() /Users/ondrej/Development/slevomat-cdn-scripts/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php:91
    1.9020   11105456   7. SlevomatCodingStandard\Sniffs\Classes\ConstantSpacingSniff->process() /Users/ondrej/Development/slevomat-cdn-scripts/vendor/squizlabs/php_codesniffer/src/Files/File.php:496
    1.9025   11105456   8. SlevomatCodingStandard\Sniffs\Classes\ConstantSpacingSniff->isNextMemberValid() /Users/ondrej/Development/slevomat-cdn-scripts/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/Classes/AbstractPropertyAndConstantSpacing.php:68
```

**Comment by kukulich** [comment]
Thank you for your report.

Fixed in https://github.com/slevomat/coding-standard/commit/e5443b923526db24ecc45b3d25bee70abf7881fd
