### ISSUE TITLE
Missing cast for PropertyTypeHint.enableNativeTypeHint from XML

### ISSUE THREAD

**Issue by Majkl578** [slevomat/coding-standard#971]
After upgrading from 6.1.5 to 6.2.0 I am seeing the following error:
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to SlevomatCodingStandard\Helpers\SniffSettingsHelper::isEnabledByPhpVersion() must be of the type bool or null, string given, called in /app/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/TypeHints/PropertyTypeHintSniff.php on line 90 and defined in /app/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffSettingsHelper.php:70
Stack trace:
#0 /app/vendor/slevomat/coding-standard/SlevomatCodingStandard/Sniffs/TypeHints/PropertyTypeHintSniff.php(90): SlevomatCodingStandard\Helpers\SniffSettingsHelper::isEnabledByPhpVersion('0', 70400)
#1 /app/vendor/squizlabs/php_codesniffer/src/Files/File.php(496): SlevomatCodingStandard\Sniffs\TypeHints\PropertyTypeHintSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 72)
#2 /app/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(129): PHP_CodeSniffer\Files\File->process()
#3 /app/vendor/squizlabs/php_codesniffer/src/Runner.php(630): PHP_CodeSniffer\Files\LocalFile->process()
#4 /app/vendor/squi in /app/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffSettingsHelper.php on line 70
```

We do explicitly disable native typehint check for PropertyTypeHint sniff - the value coming from XML doesn't seem to be casted properly:
```xml
<property name="enableNativeTypeHint" value="0"/>
```

**Comment by kukulich** [comment]
The value in the configuration should be “false”.

**Comment by Majkl578** [comment]
Was this changed in 6.2.0?

**Comment by kukulich** [comment]
No, it’s standard behaviour of PHPCS.

**Comment by Majkl578** [comment]
Then I don't understand why it was working in 6.1.5 and stopped in 6.2.0. No PHPCS update made, no configuration change made. :/ Do you have any idea what to look for?

**Comment by kukulich** [comment]
It's caused by this commit https://github.com/slevomat/coding-standard/commit/f54967777673c84706370e1ef0c9819aa1eb5982#diff-df392207b3aebabc482867be6001d9ac

However I don't think I should fix something.

**Comment by Majkl578** [comment]
> However I don't think I should fix something.

Yeah it's fine and I don't mind but a note in releese notes would probably be a good idea. :)

**Comment by punzalanrhemy** [comment]
Duplicate of #
